CREATE TABLE user (
    id CHAR(20) PRIMARY KEY,
    phone VARCHAR(13) NOT NULL,
    password VARCHAR(60) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
